services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - certbot
      - app
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email vaibhavb@gmail.com -d app.carebears.cc --agree-tos

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    env_file:
      - ./app/.env
    expose:
      - "8000" # Expose to linked services, not directly to host
    volumes:
      - ./app:/app # Mount local app code for development convenience (optional for production)
    restart: always

